// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CustomMenuStatus","status":true,"description":"自訂主選單：隱藏右側指令欄與角色職業/HP/MP","parameters":{}},
{"name":"DialogSFX","status":true,"description":"","parameters":{}}
];
